### PR TITLE
Added example for connecting to unix socket

### PR DESCRIPTION
**Pull request by cebe**
I was searching for a way to connect to redis via unix socket and I found it a bit too hard to find, so I added this here.

### CODE REVIEW

**Comment by clue** [comment]
Good catch, thank you for this contribution!

The code LGTM, but it makes me wonder if it makes more sense to just integrate this into this library. I was actually planning to integrate this somewhat similar to https://github.com/clue/php-socks-react/pull/69 and possibly use the `redis+unix://` URI scheme here.

What do you think about this? :+1:

**Comment by cebe** [comment]
of course it would make sense to add direct support for it but there are a few things that are unclear about how to handle it:

1. as you said, the scheme. `redis+unix://` would be an option, I assume there is no standard for this?
    Also is the `redis` part needed? would `unix://` be sufficient? 
2. how to specify the database? `redis+unix:///var/run/redis/redis.sock?db=2` would probably work, `redis+unix:///var/run/redis/redis.sock/2` not so much as it is indistinguishable from a path.
3. specifying auth on a socket is pointless so its fine to skip that option imo.

**Comment by cebe** [comment]
Btw, I really like how much documentation is added for all the react libraries, thanks for that! :)

**Comment by clue** [comment]
Thank you for sparking this discussion and for your positive feedback, this has just been resolved via #70! :shipit:

**Pull request closed without merging**
